x-logging:
      &default-logging
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"

networks:
    default:
        ipam:
            config:
                - subnet: 10.10.0.0/24
    internal:
        ipam:
            config:
                - subnet: 10.10.1.0/24
volumes:
    adguard:
    warp:

services:
    up:
        image: ghcr.io/ndwrd/sbbot/ng:latest
        build:
            context: dockerfile
            dockerfile: nginx.dockerfile
            args:
                image: ${IMAGE}
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - ./config/upstream.conf:/etc/nginx/nginx.conf
            - ./config/deny:/etc/nginx/deny
            - ./scripts/start_upstream.sh:/start_upstream.sh
            - ./ssh:/ssh
            - ./config/sshd_config:/etc/ssh/sshd_config
            - ./logs/:/logs/
        ports:
            - 443:443/tcp
        hostname: upstream
        container_name: gateway-${VER}
        depends_on:
            ng:
                condition: service_healthy
            sbx:
                condition: service_started
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        stop_grace_period: 1s
        command: ["/bin/sh", "/start_upstream.sh"]
        networks:
            default:
                ipv4_address: 10.10.0.10
        logging: *default-logging
    ng:
        image: ghcr.io/ndwrd/sbbot/ng:latest
        build:
            context: dockerfile
            dockerfile: nginx.dockerfile
            args:
                image: ${IMAGE}
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/override.conf:/etc/nginx/override.conf
            - ./config/location.conf:/etc/nginx/location.conf
            - ./config/nginx_default.conf:/nginx_default.conf
            - ./scripts/start_ng.sh:/start_ng.sh
            - ./certs/:/certs/
            - ./ssh:/ssh
            - ./config/sshd_config:/etc/ssh/sshd_config
            - ./logs/:/logs/
            - ./app/webapp:/app
        ports:
            - 80:80
        hostname: nginx
        container_name: web-${VER}
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        stop_grace_period: 1s
        command: ["/bin/sh", "/start_ng.sh"]
        networks:
            default:
                ipv4_address: 10.10.0.2
            internal:
                ipv4_address: 10.10.1.2
        logging: *default-logging
        depends_on:
            php:
                condition: service_healthy
            ad:
                condition: service_started
            sbx:
                condition: service_started
        healthcheck:
            test: ["CMD", "nginx", "-t"]
            interval: 10s
            timeout: 5s
            retries: 3
    php:
        image: ghcr.io/ndwrd/sbbot/php:latest
        build:
            dockerfile: dockerfile/php.dockerfile
            args:
                image: ${IMAGE}
        ports:
            - 127.0.0.1:8081:8080
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - ./config/php.ini:/etc/php81/php.ini
            - ./config/:/config/
            - ./certs/:/certs/
            - ./ssh:/ssh
            - ./app:/app
            - ./logs/:/logs/
            - ./scripts/start_php.sh:/start_php.sh
            - ./scripts/check_file.sh:/check_file.sh
            - ./version:/version
            - ./update:/update
            - ./.git:/.git
            - ./docker-compose.override.yml:/docker/compose
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - warp:/etc/warp
        environment:
            IP: ${IP}
            VER: ${VER}
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        hostname: php
        container_name: app-${VER}
        # restart: unless-stopped
        stop_grace_period: 1s
        command: ["/bin/sh", "/start_php.sh"]
        working_dir: /app
        networks:
            default:
                ipv4_address: 10.10.0.7
        extra_hosts:
            - "host.docker.internal:host-gateway"
        logging: *default-logging
        healthcheck:
            test: ["CMD", "/bin/sh", "/check_file.sh"]
            interval: 5s
            timeout: 5s
            retries: 5
    service:
        image: ghcr.io/ndwrd/sbbot/php:latest
        build:
            dockerfile: dockerfile/php.dockerfile
            args:
                image: ${IMAGE}
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - ./config/php.ini:/etc/php81/php.ini
            - ./config/:/config/
            - ./certs/:/certs/
            - ./ssh:/ssh
            - ./app:/app
            - ./logs/:/logs/
            - ./version:/version
            - ./update:/update
            - ./.git:/.git
            - ./scripts/start_service.sh:/start_service.sh
            - ./docker-compose.override.yml:/docker/compose
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            IP: ${IP}
            VER: ${VER}
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        hostname: service
        container_name: worker-${VER}
        # restart: unless-stopped
        stop_grace_period: 1s
        command: ["/bin/sh", "/start_service.sh"]
        working_dir: /app
        networks:
            default:
                ipv4_address: 10.10.0.15
        logging: *default-logging
        depends_on:
            - up
            - ng
            - php
            - ad
            - tg
            - sbx
            - dnstt
    ad:
        image: ghcr.io/ndwrd/sbbot/ad:latest
        build:
            dockerfile: dockerfile/adguard.dockerfile
            args:
                image: ${IMAGE}
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - type: volume
              target: /opt/adguardhome/work
              source: adguard
            - ./ssh:/ssh
            - ./config/sshd_config:/etc/ssh/sshd_config
            - ./config/:/config/
            - ./certs/:/certs/
            - ./logs/:/logs/
            - ./scripts/start_ad.sh:/start_ad.sh
        hostname: adguard
        container_name: dns-${VER}
        depends_on:
            php:
                condition: service_healthy
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        stop_grace_period: 1s
        networks:
            default:
                ipv4_address: 10.10.0.5
        cap_add:
            - NET_ADMIN
        entrypoint: ["/bin/sh", "/start_ad.sh"]
        logging: *default-logging
    tg:
        image: ghcr.io/ndwrd/sbbot/tg:latest
        build:
            dockerfile: dockerfile/telegram.dockerfile
        volumes:
            - ./config/.profile:/root/.bashrc:ro
            - ./ssh:/ssh
            - ./config/sshd_config:/etc/ssh/sshd_config
            - ./scripts/start_tg.sh:/start_tg.sh
            - ./config/mtprotosecret:/mtprotosecret
            - ./logs/:/logs/
        hostname: telegram
        container_name: relay-${VER}
        depends_on:
            php:
                condition: service_healthy
        environment:
            IP: ${IP}
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        stop_grace_period: 1s
        command: ["/bin/sh", "/start_tg.sh"]
        networks:
            default:
                ipv4_address: 10.10.0.8
        logging: *default-logging
    sbx:
        image: ghcr.io/ndwrd/sbbot/sbx:latest
        build:
            dockerfile: dockerfile/singbox.dockerfile
            args:
                image: ${IMAGE}
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - ./ssh:/ssh
            - ./config/sshd_config:/etc/ssh/sshd_config
            - ./config/sing-server.json:/sing.json
            - ./scripts/start_singbox.sh:/start_singbox.sh
            - ./certs/:/certs/
            - ./logs:/logs
        ports:
            - 443:443/udp
        hostname: singbox
        container_name: core-${VER}
        depends_on:
            php:
                condition: service_healthy
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        stop_grace_period: 1s
        command: ["/bin/sh", "/start_singbox.sh"]
        networks:
            default:
                ipv4_address: 10.10.0.19
            internal:
                ipv4_address: 10.10.1.19
        logging: *default-logging
    wp:
        image: ghcr.io/ndwrd/sbbot/wg:latest
        build:
            dockerfile: dockerfile/wireguard.dockerfile
            args:
                image: ${IMAGE}
        cap_add:
            - NET_ADMIN
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - ./ssh:/ssh
            - ./config/sshd_config:/etc/ssh/sshd_config
            - ./config:/config
            - ./scripts/start_wp.sh:/start_wp.sh
            - warp:/etc/warp
        hostname: warp
        container_name: net-${VER}
        command: ["/bin/sh", "/start_wp.sh"]
        depends_on:
            php:
                condition: service_healthy
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        stop_grace_period: 1s
        working_dir: /etc/warp
        networks:
            default:
                ipv4_address: 10.10.0.13
        logging: *default-logging
    dnstt:
        image: ghcr.io/ndwrd/sbbot/dnstt:latest
        build:
            dockerfile: dockerfile/dnstt.dockerfile
            args:
                image: ${IMAGE}
        volumes:
            - ./config/.profile:/root/.ashrc:ro
            - ./ssh:/ssh
            - ./logs:/logs
            - ./config/sshd_config:/etc/ssh/sshd_config
            - ./config/dnstt:/dnstt
            - ./scripts/start_dnstt.sh:/start_dnstt.sh
        hostname: dnstt
        container_name: tunnel-${VER}
        depends_on:
            php:
                condition: service_healthy
        env_file:
            - path: ./.env
              required: true # default
            - path: ./override.env
              required: false
        stop_grace_period: 1s
        command: ["/bin/sh", "/start_dnstt.sh"]
        networks:
            default:
                ipv4_address: 10.10.0.16
        logging: *default-logging
